# CTDBP Calibration Parser Example

This notebook provides an example of the use of CTDBP Calibration Parser for generating csv files from vendor documentation. The calibration coefficients can be parsed from either the vendor calibration (.cal) file, the vendor xml configuration file (.xmlcon), or from the instrument check-in capture file (either .cap, .log, or .txt). 
**===================================================================================================================**

In [1]:
# Until the module is set-up, need to 
import sys
sys.path.append('..')
sys.path.append('../Parsers/')

In [2]:
from utils import *

**===================================================================================================================**
### Data Sources and Locations
Enter the full path to where the calibration and qct files are stored. If running this example as part of the Parsers package, the relatives paths defined below should work.

In [3]:
cal_files = '../Data_Sources/CTDBP/CTDBP-C_SBE_16PlusV2_SN_16-50003_Calibration_Files_2019-01-23.zip'
qct_files = '../Data_Sources/CTDBP/3305-00102-00209-A.txt'

**===================================================================================================================**
### Create the CTDBP Calibration Object

In order to initialize the CTDBP Calibration Object requires entering the UID of the CTD instrument for which the calibration csv is going to be generated. This uid is then checked against the data parsed from the source files as a check that the expected calibration csv matches the source files where the calibration data is being parsed from.

Additionally, we will create a temp directory to output the csv files to during the course of this notebook so that they can be compared with each other at the end, and then erased.

In [4]:
from CTDBPCalibration import CTDBPCalibration

In [5]:
if not os.path.exists('/'.join((os.getcwd(),'temp'))):
    tempdir = '/'.join((os.getcwd(),'temp'))
    os.mkdir(tempdir)
else:
    tempdir = '/'.join((os.getcwd(),'temp'))

#### Calibration CSV from .cal file
First, we'll generate a calibration csv from the vendor .cal file (which is stored away in a .zip file). The steps are:
1. Initialize a CTDBPCalibration object with the instrument UID
2. Call the load_cal method with the path to where the .cal file is stored
3. Call the write_csv method with the path to where the csv calibration file should be saved to

In [6]:
ctdbp = CTDBPCalibration(uid='CGINS-CTDBPC-50003')

In [7]:
ctdbp.load_cal(cal_files)

In [8]:
ctdbp.write_csv(tempdir)

Calibration csv for CGINS-CTDBPC-50003__20190123.csv
      serial        name           value  \
0   16-50003       CC_a0   1.279318e-003
1   16-50003       CC_a1   2.674591e-004
2   16-50003       CC_a2  -3.443515e-007
3   16-50003       CC_a3   1.514413e-007
9   16-50003    CC_cpcor  -9.570000e-008
8   16-50003    CC_ctcor   3.250000e-006
4   16-50003        CC_g  -9.776009e-001
5   16-50003        CC_h   1.367521e-001
6   16-50003        CC_i  -2.643593e-004
7   16-50003        CC_j   3.768382e-005
10  16-50003      CC_pa0  -1.023306e-002
11  16-50003      CC_pa1   4.879685e-004
12  16-50003      CC_pa2  -5.587934e-012
13  16-50003    CC_ptca0   5.243844e+005
14  16-50003    CC_ptca1   3.201856e-001
15  16-50003    CC_ptca2  -6.213282e-002
16  16-50003    CC_ptcb0   2.502750e+001
17  16-50003    CC_ptcb1  -9.000000e-004
18  16-50003    CC_ptcb2   0.000000e+000
19  16-50003  CC_ptempa0  -6.002662e+001
20  16-50003  CC_ptempa1   5.486960e+001
21  16-50003  CC_ptempa2  -6.455983e-001

                                                notes
0   Source file: CTDBP-C_SBE_16PlusV2_SN_16-50003_...
1
2
3
9
8
4
5
6
7
10
11
12
13
14
15
16
17
18
19
20
21
Write CGINS-CTDBPC-50003__20190123.csv to /home/andrew/Documents/OOI-CGSN/QAQC_Sandbox/Calibration/Parsers/Examples/temp? [y/n]: y

In [9]:
# Now, lets load the csv file into a dataframe for later comparison with other calibration sources
cal = pd.read_csv('temp/CGINS-CTDBPC-50003__20190123.csv')
cal

,serial,name,value,notes
0,16-50003,CC_a0,1.279318e-03,Source file: CTDBP-C_SBE_16PlusV2_SN_16-50003_...
1,16-50003,CC_a1,2.674591e-04,NaN
2,16-50003,CC_a2,-3.443515e-07,NaN
3,16-50003,CC_a3,1.514413e-07,NaN
4,16-50003,CC_cpcor,-9.570000e-08,NaN
5,16-50003,CC_ctcor,3.250000e-06,NaN
6,16-50003,CC_g,-9.776009e-01,NaN
7,16-50003,CC_h,1.367521e-01,NaN
8,16-50003,CC_i,-2.643593e-04,NaN
9,16-50003,CC_j,3.768382e-05,NaN
10,16-50003,CC_pa0,-1.023306e-02,NaN
11,16-50003,CC_pa1,4.879685e-04,NaN
12,16-50003,CC_pa2,-5.587934e-12,NaN
13,16-50003,CC_ptca0,5.243844e+05,NaN
14,16-50003,CC_ptca1,3.201856e-01,NaN
15,16-50003,CC_ptca2,-6.213282e-02,NaN
16,16-50003,CC_ptcb0,2.502750e+01,NaN
17,16-50003,CC_ptcb1,-9.000000e-04,NaN
18,16-50003,CC_ptcb2,0.000000e+00,NaN
19,16-50003,CC_ptempa0,-6.002662e+01,NaN
20,16-50003,CC_ptempa1,5.486960e+01,NaN
21,16-50003,CC_ptempa2,-6.455983e-01,NaN

#### Calibration CSV from .xmlcon file
First, we'll generate a calibration csv from the vendor .xmlcon file (which is stored away in a .zip file). The steps are:
1. Initialize a CTDBPCalibration object with the instrument UID
2. Call the load_xmlcon method with the path to where the .xmlcon file is stored
3. Call the write_csv method with the path to where the csv calibration file should be saved to

In [10]:
ctdbp = CTDBPCalibration(uid='CGINS-CTDBPC-50003')

In [11]:
ctdbp.load_xml(cal_files)

In [12]:
ctdbp.write_csv(tempdir)

Calibration csv for CGINS-CTDBPC-50003__20190123.csv
      serial        name             value  \
0   16-50003       CC_a0   1.27931792E-003
1   16-50003       CC_a1   2.67459131E-004
2   16-50003       CC_a2  -3.44351535E-007
3   16-50003       CC_a3   1.51441267E-007
4   16-50003    CC_cpcor  -9.57000000E-008
9   16-50003    CC_ctcor       3.2500E-006
5   16-50003        CC_g  -9.77600863E-001
6   16-50003        CC_h   1.36752070E-001
7   16-50003        CC_i  -2.64359259E-004
8   16-50003        CC_j   3.76838203E-005
10  16-50003      CC_pa0  -1.02330555E-002
11  16-50003      CC_pa1   4.87968524E-004
12  16-50003      CC_pa2  -5.58793402E-012
16  16-50003    CC_ptca0   5.24384369E+005
17  16-50003    CC_ptca1   3.20185561E-001
18  16-50003    CC_ptca2  -6.21328165E-002
19  16-50003    CC_ptcb0   2.50275000E+001
20  16-50003    CC_ptcb1  -9.00000000E-004
21  16-50003    CC_ptcb2   0.00000000E+000
13  16-50003  CC_ptempa0  -6.00266156E+001
14  16-50003  CC_ptempa1   5.48696034E+001
15  16-50003  CC_ptempa2  -6.45598270E-001

                                                notes
0   Source file: CTDBP-C_SBE_16PlusV2_SN_16-50003_...
1
2
3
4
9
5
6
7
8
10
11
12
16
17
18
19
20
21
13
14
15
Write CGINS-CTDBPC-50003__20190123.csv to /home/andrew/Documents/OOI-CGSN/QAQC_Sandbox/Calibration/Parsers/Examples/temp? [y/n]: y

In [13]:
# Now, load the csv back into pandas dataframe for later comparison with other methods
xml = pd.read_csv('temp/CGINS-CTDBPC-50003__20190123.csv')
xml

,serial,name,value,notes
0,16-50003,CC_a0,1.279318e-03,Source file: CTDBP-C_SBE_16PlusV2_SN_16-50003_...
1,16-50003,CC_a1,2.674591e-04,NaN
2,16-50003,CC_a2,-3.443515e-07,NaN
3,16-50003,CC_a3,1.514413e-07,NaN
4,16-50003,CC_cpcor,-9.570000e-08,NaN
5,16-50003,CC_ctcor,3.250000e-06,NaN
6,16-50003,CC_g,-9.776009e-01,NaN
7,16-50003,CC_h,1.367521e-01,NaN
8,16-50003,CC_i,-2.643593e-04,NaN
9,16-50003,CC_j,3.768382e-05,NaN
10,16-50003,CC_pa0,-1.023306e-02,NaN
11,16-50003,CC_pa1,4.879685e-04,NaN
12,16-50003,CC_pa2,-5.587934e-12,NaN
13,16-50003,CC_ptca0,5.243844e+05,NaN
14,16-50003,CC_ptca1,3.201856e-01,NaN
15,16-50003,CC_ptca2,-6.213282e-02,NaN
16,16-50003,CC_ptcb0,2.502750e+01,NaN
17,16-50003,CC_ptcb1,-9.000000e-04,NaN
18,16-50003,CC_ptcb2,0.000000e+00,NaN
19,16-50003,CC_ptempa0,-6.002662e+01,NaN
20,16-50003,CC_ptempa1,5.486960e+01,NaN
21,16-50003,CC_ptempa2,-6.455983e-01,NaN

#### Calibration CSV from QCT file
First, we'll generate a calibration csv from the vendor .xmlcon file (which is stored away in a .zip file). The steps are:
1. Initialize a CTDBPCalibration object with the instrument UID
2. Call the load_qct method with the path to where the QCT file is stored
3. Call the write_csv method with the path to where the csv calibration file should be saved to

In [14]:
ctdbp = CTDBPCalibration(uid='CGINS-CTDBPC-50003')

In [15]:
ctdbp.load_qct(qct_files)

In [17]:
ctdbp.write_csv(tempdir)

Calibration csv for CGINS-CTDBPC-50003__20190123.csv
      serial        name          value  \
0   16-50003       CC_a0   1.279318e-03
1   16-50003       CC_a1   2.674591e-04
2   16-50003       CC_a2  -3.443515e-07
3   16-50003       CC_a3   1.514413e-07
8   16-50003    CC_cpcor  -9.570000e-08
9   16-50003    CC_ctcor   3.250000e-06
4   16-50003        CC_g  -9.776009e-01
5   16-50003        CC_h   1.367521e-01
6   16-50003        CC_i  -2.643593e-04
7   16-50003        CC_j   3.768382e-05
10  16-50003      CC_pa0  -1.023306e-02
11  16-50003      CC_pa1   4.879685e-04
12  16-50003      CC_pa2  -5.587934e-12
13  16-50003    CC_ptca0   5.243845e+05
14  16-50003    CC_ptca1   3.201856e-01
15  16-50003    CC_ptca2  -6.213282e-02
16  16-50003    CC_ptcb0   2.502750e+01
17  16-50003    CC_ptcb1  -9.000000e-04
18  16-50003    CC_ptcb2   0.000000e+00
19  16-50003  CC_ptempa0  -6.002662e+01
20  16-50003  CC_ptempa1   5.486960e+01
21  16-50003  CC_ptempa2  -6.455983e-01

                                          notes
0   Source file: CTDBP > 3305-00102-00209-A.txt
1
2
3
8
9
4
5
6
7
10
11
12
13
14
15
16
17
18
19
20
21
Write CGINS-CTDBPC-50003__20190123.csv to /home/andrew/Documents/OOI-CGSN/QAQC_Sandbox/Calibration/Parsers/Examples/temp? [y/n]: y

In [19]:
qct = pd.read_csv('temp/CGINS-CTDBPC-50003__20190123.csv')
qct

,serial,name,value,notes
0,16-50003,CC_a0,1.279318e-03,Source file: CTDBP > 3305-00102-00209-A.txt
1,16-50003,CC_a1,2.674591e-04,NaN
2,16-50003,CC_a2,-3.443515e-07,NaN
3,16-50003,CC_a3,1.514413e-07,NaN
4,16-50003,CC_cpcor,-9.570000e-08,NaN
5,16-50003,CC_ctcor,3.250000e-06,NaN
6,16-50003,CC_g,-9.776009e-01,NaN
7,16-50003,CC_h,1.367521e-01,NaN
8,16-50003,CC_i,-2.643593e-04,NaN
9,16-50003,CC_j,3.768382e-05,NaN
10,16-50003,CC_pa0,-1.023306e-02,NaN
11,16-50003,CC_pa1,4.879685e-04,NaN
12,16-50003,CC_pa2,-5.587934e-12,NaN
13,16-50003,CC_ptca0,5.243845e+05,NaN
14,16-50003,CC_ptca1,3.201856e-01,NaN
15,16-50003,CC_ptca2,-6.213282e-02,NaN
16,16-50003,CC_ptcb0,2.502750e+01,NaN
17,16-50003,CC_ptcb1,-9.000000e-04,NaN
18,16-50003,CC_ptcb2,0.000000e+00,NaN
19,16-50003,CC_ptempa0,-6.002662e+01,NaN
20,16-50003,CC_ptempa1,5.486960e+01,NaN
21,16-50003,CC_ptempa2,-6.455983e-01,NaN

**===================================================================================================================**
#### Comparison of Methods
Now, we can compare the generated csvs from each of the vendor sources and check that they are in agreement.

In [20]:
cal == xml

    serial  name  value  notes
0     True  True  False  False
1     True  True  False  False
2     True  True  False  False
3     True  True  False  False
4     True  True   True  False
5     True  True   True  False
6     True  True  False  False
7     True  True  False  False
8     True  True  False  False
9     True  True  False  False
10    True  True  False  False
11    True  True  False  False
12    True  True  False  False
13    True  True  False  False
14    True  True  False  False
15    True  True  False  False
16    True  True   True  False
17    True  True   True  False
18    True  True   True  False
19    True  True  False  False
20    True  True  False  False
21    True  True  False  False

In [21]:
qct == cal

    serial  name  value  notes
0     True  True   True  False
1     True  True   True  False
2     True  True   True  False
3     True  True   True  False
4     True  True   True  False
5     True  True   True  False
6     True  True   True  False
7     True  True   True  False
8     True  True   True  False
9     True  True   True  False
10    True  True   True  False
11    True  True   True  False
12    True  True   True  False
13    True  True  False  False
14    True  True   True  False
15    True  True   True  False
16    True  True   True  False
17    True  True   True  False
18    True  True   True  False
19    True  True   True  False
20    True  True   True  False
21    True  True   True  False

In [22]:
qct == xml

    serial  name  value  notes
0     True  True  False  False
1     True  True  False  False
2     True  True  False  False
3     True  True  False  False
4     True  True   True  False
5     True  True   True  False
6     True  True  False  False
7     True  True  False  False
8     True  True  False  False
9     True  True  False  False
10    True  True  False  False
11    True  True  False  False
12    True  True  False  False
13    True  True  False  False
14    True  True  False  False
15    True  True  False  False
16    True  True   True  False
17    True  True   True  False
18    True  True   True  False
19    True  True  False  False
20    True  True  False  False
21    True  True  False  False

So, we see that although the coefficient serial numbers and names match, that the values don't. Why is that? Probably due to rounding *inherent to the source file.* We can check this by using the numpy function is_close() with a relatively tight difference threshold (0.01%) as a further check:

In [23]:
import numpy as np

In [24]:
np.isclose(cal['value'],xml['value'])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [25]:
np.isclose(cal['value'],qct['value'])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [26]:
np.isclose(xml['value'],qct['value'])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [28]:
# And delete the temporary folder
shutil.rmtree(tempdir)